# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initializeTerralib <- function() {
    invisible(.Call('TrajDataAccess_initializeTerralib', PACKAGE = 'TrajDataAccess'))
}

finalizeTerralib <- function() {
    invisible(.Call('TrajDataAccess_finalizeTerralib', PACKAGE = 'TrajDataAccess'))
}

getTrajectoryByTerralibXPtr <- function(datasource, dataset) {
    .Call('TrajDataAccess_getTrajectoryByTerralibXPtr', PACKAGE = 'TrajDataAccess', datasource, dataset)
}

getTrajectoryByTerralib <- function(datasource, dataset) {
    .Call('TrajDataAccess_getTrajectoryByTerralib', PACKAGE = 'TrajDataAccess', datasource, dataset)
}

getTrajectoryByTerralibTraj <- function() {
    .Call('TrajDataAccess_getTrajectoryByTerralibTraj', PACKAGE = 'TrajDataAccess')
}

getTrajectoryByTerralibStBoxXPtr <- function(datasource, dataset, envelope, period) {
    .Call('TrajDataAccess_getTrajectoryByTerralibStBoxXPtr', PACKAGE = 'TrajDataAccess', datasource, dataset, envelope, period)
}

getTrajectoryByTerralibStBox <- function(datasource, dataset, envelope, period) {
    .Call('TrajDataAccess_getTrajectoryByTerralibStBox', PACKAGE = 'TrajDataAccess', datasource, dataset, envelope, period)
}

LoadTrajectoryDataSetFromPostGIS <- function() {
    invisible(.Call('TrajDataAccess_LoadTrajectoryDataSetFromPostGIS', PACKAGE = 'TrajDataAccess'))
}

getTrajectoryFromKML <- function() {
    .Call('TrajDataAccess_getTrajectoryFromKML', PACKAGE = 'TrajDataAccess')
}

getTrajectoryFromDB <- function(tableName) {
    .Call('TrajDataAccess_getTrajectoryFromDB', PACKAGE = 'TrajDataAccess', tableName)
}

getTrajectoryKMLAsText <- function() {
    .Call('TrajDataAccess_getTrajectoryKMLAsText', PACKAGE = 'TrajDataAccess')
}

getTrajectoryKMLAsText2 <- function(dataset, id) {
    .Call('TrajDataAccess_getTrajectoryKMLAsText2', PACKAGE = 'TrajDataAccess', dataset, id)
}

getTrajectoryDBAsText <- function(tableName) {
    .Call('TrajDataAccess_getTrajectoryDBAsText', PACKAGE = 'TrajDataAccess', tableName)
}

getTrajectoryKMLAsVectorList <- function() {
    .Call('TrajDataAccess_getTrajectoryKMLAsVectorList', PACKAGE = 'TrajDataAccess')
}

getTrajectoryGivenKMLAsVectorList <- function(selected, name) {
    .Call('TrajDataAccess_getTrajectoryGivenKMLAsVectorList', PACKAGE = 'TrajDataAccess', selected, name)
}

getTrajectoryDBAsVectorList <- function(tableName) {
    .Call('TrajDataAccess_getTrajectoryDBAsVectorList', PACKAGE = 'TrajDataAccess', tableName)
}

getTrajectoryKMLAsListOfLists <- function() {
    .Call('TrajDataAccess_getTrajectoryKMLAsListOfLists', PACKAGE = 'TrajDataAccess')
}

