# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initializeTerralib <- function() {
    invisible(.Call('TrajDataAccess_initializeTerralib', PACKAGE = 'TrajDataAccess'))
}

finalizeTerralib <- function() {
    invisible(.Call('TrajDataAccess_finalizeTerralib', PACKAGE = 'TrajDataAccess'))
}

getTrajectoryByTerralibXPtr <- function(datasource, dataset) {
    .Call('TrajDataAccess_getTrajectoryByTerralibXPtr', PACKAGE = 'TrajDataAccess', datasource, dataset)
}

getTrajectoryByTerralib <- function(datasource, dataset) {
    .Call('TrajDataAccess_getTrajectoryByTerralib', PACKAGE = 'TrajDataAccess', datasource, dataset)
}

getTrajectoryByTerralibTraj <- function() {
    .Call('TrajDataAccess_getTrajectoryByTerralibTraj', PACKAGE = 'TrajDataAccess')
}

getSubTrajectoryByTerralibTraj <- function(datasource, dataset) {
    .Call('TrajDataAccess_getSubTrajectoryByTerralibTraj', PACKAGE = 'TrajDataAccess', datasource, dataset)
}

getTrajectoryByTerralibStBoxXPtr <- function(datasource, dataset, envelope, period) {
    .Call('TrajDataAccess_getTrajectoryByTerralibStBoxXPtr', PACKAGE = 'TrajDataAccess', datasource, dataset, envelope, period)
}

getTrajectoryByTerralibStBox <- function(datasource, dataset, envelope, period) {
    .Call('TrajDataAccess_getTrajectoryByTerralibStBox', PACKAGE = 'TrajDataAccess', datasource, dataset, envelope, period)
}

LoadTrajectoryDataSetFromPostGIS <- function() {
    invisible(.Call('TrajDataAccess_LoadTrajectoryDataSetFromPostGIS', PACKAGE = 'TrajDataAccess'))
}

LoadTrajectoryDataSetFromPostGIS2 <- function(datasource, dataset) {
    invisible(.Call('TrajDataAccess_LoadTrajectoryDataSetFromPostGIS2', PACKAGE = 'TrajDataAccess', datasource, dataset))
}

receiveReturnXPTR <- function(teste) {
    .Call('TrajDataAccess_receiveReturnXPTR', PACKAGE = 'TrajDataAccess', teste)
}

receiveReturnPartsXPTR <- function(teste) {
    .Call('TrajDataAccess_receiveReturnPartsXPTR', PACKAGE = 'TrajDataAccess', teste)
}

getPartsXPTR <- function(teste, division) {
    .Call('TrajDataAccess_getPartsXPTR', PACKAGE = 'TrajDataAccess', teste, division)
}

getSpecificPartsXPTR <- function(teste, part, division) {
    .Call('TrajDataAccess_getSpecificPartsXPTR', PACKAGE = 'TrajDataAccess', teste, part, division)
}

getTrajectoryByTrajID <- function(datasource, dataset, id) {
    .Call('TrajDataAccess_getTrajectoryByTrajID', PACKAGE = 'TrajDataAccess', datasource, dataset, id)
}

getTrajectoryByObjID <- function(datasource, dataset, id) {
    .Call('TrajDataAccess_getTrajectoryByObjID', PACKAGE = 'TrajDataAccess', datasource, dataset, id)
}

getSpecificPartsDB <- function(datasource, dataset, part, division) {
    .Call('TrajDataAccess_getSpecificPartsDB', PACKAGE = 'TrajDataAccess', datasource, dataset, part, division)
}

getTrajectoryFromKML <- function() {
    .Call('TrajDataAccess_getTrajectoryFromKML', PACKAGE = 'TrajDataAccess')
}

getTrajectoryFromDB <- function(tableName) {
    .Call('TrajDataAccess_getTrajectoryFromDB', PACKAGE = 'TrajDataAccess', tableName)
}

getTrajectoryKMLAsText <- function() {
    .Call('TrajDataAccess_getTrajectoryKMLAsText', PACKAGE = 'TrajDataAccess')
}

getTrajectoryKMLAsText2 <- function(dataset, id) {
    .Call('TrajDataAccess_getTrajectoryKMLAsText2', PACKAGE = 'TrajDataAccess', dataset, id)
}

getTrajectoryDBAsText <- function(tableName) {
    .Call('TrajDataAccess_getTrajectoryDBAsText', PACKAGE = 'TrajDataAccess', tableName)
}

getTrajectoryKMLAsVectorList <- function() {
    .Call('TrajDataAccess_getTrajectoryKMLAsVectorList', PACKAGE = 'TrajDataAccess')
}

getTrajectoryGivenKMLAsVectorList <- function(selected, name) {
    .Call('TrajDataAccess_getTrajectoryGivenKMLAsVectorList', PACKAGE = 'TrajDataAccess', selected, name)
}

getTrajectoryDBAsVectorList <- function(tableName) {
    .Call('TrajDataAccess_getTrajectoryDBAsVectorList', PACKAGE = 'TrajDataAccess', tableName)
}

getTrajectoryKMLAsListOfLists <- function() {
    .Call('TrajDataAccess_getTrajectoryKMLAsListOfLists', PACKAGE = 'TrajDataAccess')
}

